manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: m165437
      url-base: https://github.com/M165437

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    # módulo extra com o shield
    - name: nice-view-gem
      remote: m165437
      revision: main
      path: modules/nice-view-gem   # <-- novo

  self:
    path: config
